<head>
	<meta charset="utf-8">
	<script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<link rel="icon" href="img/favicon.png">
	<title>Massage bien-être: Acceuil - Institut massage - Soins</title>
</head>

<body>
	<header>
		<div class="logo">
			<a href="index.php"><img src="img/logo.jpg" alt="logo"></a>
		</div>
		<nav class="menuburgeur">
			<div class="menu">
				<ul>
					<li><a class="active" href="index.php"><i class="fas fa-house-damage"></i></a></li>
				<li class="menuTarif"><a href="soins.php">Soins</a>
				        <ul>
							<li><a href="gestionsoins.php">Gestion de soins</i></a></li>
							<li><a href="modifsoins.php">Modifier Soins</a></li>
							<li><a href="ajoutsoins.php">Ajouter un soins</a></li>
						</ul>
				</li>
					<li class="menuTarif"><a href="#">Catégories</a></li>
					<li class="menulivreDor"><a href="livredor.php">Livre d'or</a></li>
					<li class="menulivreDor"><a href="listecommande.php">Commandes</a></li>
			</div>
		</nav>
	</header>
	<main>
		<div class="container">
		<h2> Ajouter un soin</h2>
		<h3>bonjour Admin <a>deconnexion</a></h3>
		<p>Votre avis sera publié aprés validation par le modérateur</p>
		<p><span>(*)</span> Champs obligatoires.</p>
							<form action="ajoutsoins.php" method="post">
								<p><label>titre<span>(*)</span></label></p>
								<input class="name" type="text" name="name" size="40" /><br>
                                <p><label>Description<span>(*)</span></label></p>
	                            <textarea name="message" rows="8" cols="80" required></textarea></br>
								<p><label>Durée en minutes<span>(*)</span></label></p>
								<input class="email" type="number" name="time" size="40"><br>
								<p><label>prix en euros</label></p>
								<input type="number" name="price" size="40"><br>
								<p><label>catégories<span>(*)</span></label></p>
								<select class="sujet" name="categories">
									<option class="sujet" value="1">massage visage</option>
									<option class="sujet" value="2">massage corps</option>
									<option class="sujet" value="3">massage dos</option>
								</select></br>
								<p><label>photo</label></p>
								<input type="file" name="photo"><p>aucun fichier sélectionner</p>
								<p><label>publié</label></p>
								<input type="radio" name="choice" value="1">oui<input type="radio" name="choice" value="2">non
								<p class="centre"><button type="submit" class="boutton2" name="boutton2" value="envoyer"><i class="fas fa-paper-plane"></i> envoyer</button></p>
							</form>
							
	</div>
	</main>