<?php include ("header.php");?>
<main>
		<picture>
			<source media="(min-width: 1024px)" srcset="img/banner-desktop.jpg">
			<source media="(min-width: 768px) and (max-width: 1023px)" srcset="img/banner-tablette.jpg">
			<img src="img/banner-mobile.jpg" alt="banner_Page">
		</picture>
		<div id="scroll1">
			<a href="#top"><img src="img/arrow-top.png" alt="scroll"></a>
		</div>
		<div class="container">
			<h1>Stéphanie Dessart</h1>
			<div id="propos">
				<img src="img/stephanie-dessart.jpg" alt="stephanie_dessart" class="stephanie">
				<div id="histoire">
					<h2>Praticienne en massage de bien-être</h2>
					<p>C'est lors d'un voyage en Thailande en 2000 que j'ai découvert le massage et ses bienfaits.</p>
					<p>Ancienne préparatrice en pharmacie, conseillère en produits cosmétiques pendant 15 ans et attentive à l’utilité bénéfique des huiles essentielles et des plantes, j’ai décidé d’approfondir mes connaissances dans le domaine du bien-être et
						des soins liés à la détente.</p>
					<p>C’est pourquoi aujourd’hui, je me suis spécialisée dans les soins visage et corps relaxants personnalisés grâce à la technique ayurvédique qui consiste à choisir les produits adaptés selon le tempérament de la personne, afin que celle-ci
						soit totalement réceptive aux produits choisis et soit en harmonie avec son corps, pour retrouver son équilibre.</p>
				</div>
			</div>
		</div>
	</main>
<?php include ("footer.php");?>