<?php include ("header.php");?>
<!DOCTYPE html>
<html>
<head>
	<title>session user</title>
</head>
<body>
	<div class="container">
	<h1>Espace client</h1>
	<h2>Page Connexion</h2>
	<?php if(isset($_SESSION['login'])):?>
    <p>bonjour Franck</p>
    <button><a href="deconnecte.php">Se deconnecter</a></button>
    <?php else:?>
	<form action="connexion.php" method="post">
		<label for="nom">login</label>
		<input type="text"name="login">
		<label for="pass">mot de passe:</label>
		<input type="password" id="pass" name="password">
		<button>Se connecter</button>
	</form>
	<h2>Creer un compte</h2>
	<form action="connexion.php" method="post">
		<p><label for="nom">nom:</label></p>
		<p><input type="text" name="nom"></p>
		<p><label for="nom">prenom:</label></p>
		<p><input type="text" name="prenom"></p>
		<p><label for="nom">adresse:</label></p>
		<p><input type="text" name="adresse"></p>
		<p><label for="nom">code postal:</label></p>
		<p><input type="number" name="code"></p>
		<p><label for="nom">ville:</label></p>
		<p><input type="text" name="ville"></p>
		<p><label for="nom">telephone:</label></p>
		<p><input type="number" name="tel"></p>
		<p><label for="nom">email:</label></p>
		<p><input type="mail" name="email"></p>
		<p><label for="pass">mot de passe:</label></p>
		<p><input type="password" id="pass" name="password"></p>
		<p><button>Creer un compte</button></p>
	</form>
	</div>
	<?php endif;?>   
</body>
<?php include ("footer.php");?>
</html>