<?php include ("header.php");?>
<main>
		<picture>
			<source media="(min-width: 1024px)" srcset="img/banner-desktop.jpg">
			<source media="(min-width: 768px) and (max-width: 1023px)" srcset="img/banner-tablette.jpg">
			<img src="img/banner-mobile.jpg" alt="banner_Page">
		</picture>
		<div id="scroll1">
			<a href="#top"><img src="img/arrow-top.png" alt="scroll"></a>
		</div>
		<div class="container">
			<h1>Me Contacter</h1>
			<div class="renseignements">
				<div class="contact">
					<h2>Mes coordonnées</h2>
					<p class="italique"><i class="fas fa-map-marker"></i> 6 Avenue Halley<br> 59650 Villeneuve d'Ascq</p>
					<p><i class="far fa-envelope-open"></i> <a href="mailto:info@soinsetsens.fr">Email : info@soinsetsens.fr</a></p>
					<p><i class="fas fa-phone"></i>Téléphone : <a href="tel:+33662727500"> 06 62 72 75 00</a></p>
					<p>Vous pouvez aussi remplir le formulaire ci-dessous.<p>
							<p><span>(*)</span> Champs obligatoires.</p>
							<form>
								<p><label>Nom<span>(*)</span></label></p>
								<input class="name" type="text" name="name" size="40" /><br>
								<p><label>Email<span>(*)</span></label></p>
								<input class="email" type="Email" name="Email" size="40"><br>
								<p><label>Telephone</label></p>
								<input class="telephone" type="tel" name="telephone" size="40"><br>
								<p><label>Sujet<span>(*)</span></label></p>
								<select class="sujet" name="sujet">
									<option class="sujet" value="lundi" selected="selected">--Veuillez faire un choix---</option>
									<option class="sujet" value="mardi">mardi</option>
								</select>
								<p><label>Message<span>(*)</span></label></p>
	               <textarea name="message" rows="8" cols="80" required></textarea>
								<p><input type="checkbox" name="message"> En soumettant ce formlaire, j'accepte la <a href="politique-de-confidentialite.html">politique de confidentialité</a> du site, j'accepte que les informations saisies spoient exploitées dans le
									cadre de la relation qui peut en
									découler.</p>
							</form>
							<p class="centre"><button type="submit" class="boutton2" name="boutton2" value="envoyer"><i class="fas fa-paper-plane"></i> envoyer</button></p>
				</div>
				<div class="horaires">
					<h2>Horaires d'ouverture</h2>
					<ul><li>Lundi: de 9h30 à 19h30</li>
					<li>Mardi: de 9h30 à 19h30</li>
					<li>Mercredi: de 9h30 à 19h30</li>
					<li>jeudi: de 9h30 à 19h30</li>
					<li>Vendredi: de 9h30 à 20h30</li>
					<li>Samedi: de 9h30 à 12h30</li>
					<span><li>Dimanche fermé</li>	</span></ul>

					<h2>Plan d'accées</h2>
					<iframe
						src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2532.046402896127!2d3.1504495159003727!3d50.6076752839042!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c2d7b1bb55315b%3A0x4b45dfe6209b7bbd!2s6+Avenue+Halley%2C+59650+Villeneuve-d&#39;Ascq!5e0!3m2!1sfr!2sfr!4v1552916714481"
						width="600" height="450" style="border:0" allowfullscreen></iframe>
				</div>
			</div>
		</div>
	</main>
<?php include ("footer.php");?>
