<?php include ("header.php");?>
<main>
		<div class="slide">
			<div id="precedent">
				<i class="fas fa-chevron-left"></i>
			</div>
			<div class="text">
				<div></div>
				<div class="textSlide">
					<h2>vous souhaitez prendre un rendez vous?</h2>
					<p> je vous reçois au cabinet et me deplace en entreprise ou a domicile</p>
					<button><a href="index.html">Découvrez mes prestations</a></button>
				</div>
				<div class="points">
					<div id="un"> <i class="fas fa-circle"></i></div>
					<div id="deux"><i class="fas fa-circle"></i></div>
					<div id="trois"><i class="fas fa-circle"></i></div>
				</div>
			</div>

			<div id="suivant">
				<i class="fas fa-chevron-right"></i>
			</div>
			<img src="img/slides/soins-et-sens.jpg" alt="soins_et_sens">
		</div>
		<div id="scroll1">
			<a href="#top"><img src="img/arrow-top.png" alt="scroll"></a>
		</div>
		<div class="container">
			<h2>Institut de massage</h2>
			<div class="presentation">
				<article>
					<h2>Prendre soin de toi</h2>
					<p><strong>Soins et sens</strong> est un salon de relaxation totalement aménagé pour vous faitre voyager dans le pays du <strong>bien-être.</strong>
						<p> Situté a villeneuve d'ascq pres de l'hotel olivarius, â proximité du parc scientifique de la haute borne,et de synergy parc, il est implanté au sein des entreprises afin que vous puissiez vous accorder une pause detente le midi ou
							apres une journée de travail.
							<p>les soins de bien être provoquent un sentiment de d'évasion, ils vous permettent de vous detendre, de vous dé-stresser et d'être plus éfficace</p>
							<p> au plaisir de vous acceuillir</p>
				</article>
				<aside>
					<h2>Horaires d'ouverture</h2>
					<ul><li>Lundi: de 9h30 à 19h30</li>
					<li>Mardi: de 9h30 à 19h30</li>
					<li>Mercredi: de 9h30 à 19h30</li>
					<li>jeudi: de 9h30 à 19h30</li>
					<li>Vendredi: de 9h30 à 20h30</li>
					<li>Samedi: de 9h30 à 12h30</li>
					<span><li>Dimanche fermé</li></span></ul>
				</aside>
			</div>
		</div>
		<div class="promo">
			<h2>Bientôt la fête des mères</h2>
			<p>Offrez lui un moment de détente !</p>
		</div>
		<div class="container">
			<h2 class="centre">Mes soins</h2>
			<div class="mes_soins">
				<?php foreach ($table AS $ta):?>
				<article class="article_msg_vsg">
					<h3><?=$ta['nom_soins']?></h3>
					<img src=<?=$ta['photo_soins']?>>
					<p><?=$ta['desc_soins']?></p>
					<p class="centre"><button class="style" type="button">En savoir <i class="fas fa-plus-circle"></i></button></p>
				</article>
				
			<?php endforeach;?>
		</div>
		</div>
		<div class="container">
			<div class="rdv_cadeau">
				<div class="prendre_rdv">
					<h3><i class="fas fa-calendar"></i> prendre rendez-vous</h3>
					<p>Pour prendre rendez-vous, je vous invite à me téléphoner ou m'envoy un texto au 06 62 72 75 00.</p>
					<p>Vous pouvez également <a href="https://www.resalib.fr/" target="_blank">réserver votre séance</a> sur Resalib.</p>
				</div>
				<div class="idee_cadeau">
					<h3><i class="fas fa-gift"></i> L'idée cadeau</h3>
					<p>Pensez-y à l'occasion d'un mariage, d'un anniversaire, de la Saint-Valentin, de la fête des mères ou de la fête des pères, comme cadeau de Noël ou pour les fêtes de fin d'année..</p>
					<p>Achetez un bon cadeau sur la <a href="Boutique.html">boutique en ligne</a>.</p>
				</div>
			</div>
		</div>
		<iframe
			src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2532.046402896127!2d3.1504495159003727!3d50.6076752839042!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c2d7b1bb55315b%3A0x4b45dfe6209b7bbd!2s6+Avenue+Halley%2C+59650+Villeneuve-d&#39;Ascq!5e0!3m2!1sfr!2sfr!4v1552916714481"
			width="600" height="450" style="border:0" allowfullscreen></iframe>
	</main>
<?php include ("footer.php");?>