<?php include ("header.php");?>
<main>
    <picture>
      <source media="(min-width: 1024px)" srcset="img/banner-desktop.jpg">
      <source media="(min-width: 768px) and (max-width: 1023px)" srcset="img/banner-tablette.jpg">
      <img src="img/banner-mobile.jpg" alt="banner_Page">
    </picture>
    <div id="scroll1">
      <a href="#top"><img src="img/arrow-top.png" alt="scroll"></a>
    </div>
    <div class="container">
      <h1>Mentions légales</h1>
      <div class="mentions">
        <div class="siege_social">
          <h2>Siège social</h2>
          <P>Entreprise individuelle</P>
          <p>Numéro de SIRET : 431 303 775 000 16</p>
          <p class="italique"><i class="fas fa-map-marker"></i> 6 Avenue Halley 59650 Villeneuve d'Ascq</p>
          <p>Consulter notre<a href="politique-de-confidentialite.html"> politique de confidentialité</a></p>
        </div>
        <div class="editeur_site">
          <h2>Éditeur du site</h2>
          <h3>Ifocop</h3>
          <p class="italique">27 Rue Denis Papin <br>59650 Villeneuve-d'Ascq </p>
          <p><i class="fas fa-phone"></i><a href="tel:+330320476092"> 03 20 47 60 92</a></p>
        </div>
        <div class="hebergeur">
          <h2>Hébergement du site</h2>
          <P>OVH</P>
          <p>Numéro de SIRET : 431 303 775 000 16</p>
          <p class="italique"> 2 rue Kellermann<br> 59100 ROUBAIX</p>
          <p>Site web :<a href="https://www.ovh.com/fr/" target="_blank">www.ovh.com</a></p>
        </div>
      </div>
    </div>
  </main>
<?php include ("footer.php");?>
